# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(731, 550)
        self.Label_UserPhoto = QtWidgets.QLabel(Form)
        self.Label_UserPhoto.setGeometry(QtCore.QRect(80, 100, 191, 241))
        self.Label_UserPhoto.setText("")
        self.Label_UserPhoto.setPixmap(QtGui.QPixmap("User.png"))
        self.Label_UserPhoto.setObjectName("Label_UserPhoto")
        self.Label_UserName = QtWidgets.QLabel(Form)
        self.Label_UserName.setGeometry(QtCore.QRect(360, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_UserName.setFont(font)
        self.Label_UserName.setObjectName("Label_UserName")
        self.Label_UserMessage = QtWidgets.QLabel(Form)
        self.Label_UserMessage.setGeometry(QtCore.QRect(360, 250, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_UserMessage.setFont(font)
        self.Label_UserMessage.setObjectName("Label_UserMessage")
        self.Label_UserName_2 = QtWidgets.QLabel(Form)
        self.Label_UserName_2.setGeometry(QtCore.QRect(430, 180, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_UserName_2.setFont(font)
        self.Label_UserName_2.setObjectName("Label_UserName_2")
        self.Label_UserMassege_2 = QtWidgets.QLabel(Form)
        self.Label_UserMassege_2.setGeometry(QtCore.QRect(430, 250, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_UserMassege_2.setFont(font)
        self.Label_UserMassege_2.setObjectName("Label_UserMassege_2")
        self.Label_Show = QtWidgets.QLabel(Form)
        self.Label_Show.setGeometry(QtCore.QRect(60, 30, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Show.setFont(font)
        self.Label_Show.setObjectName("Label_Show")
        self.Label_SetPhoto = QtWidgets.QLabel(Form)
        self.Label_SetPhoto.setGeometry(QtCore.QRect(80, 390, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_SetPhoto.setFont(font)
        self.Label_SetPhoto.setObjectName("Label_SetPhoto")
        self.lineEdit_SetPhoto = QtWidgets.QLineEdit(Form)
        self.lineEdit_SetPhoto.setGeometry(QtCore.QRect(200, 390, 351, 31))
        self.lineEdit_SetPhoto.setInputMask("")
        self.lineEdit_SetPhoto.setObjectName("lineEdit_SetPhoto")
        self.pushButton_SetPhoto = QtWidgets.QPushButton(Form)
        self.pushButton_SetPhoto.setGeometry(QtCore.QRect(570, 390, 93, 28))
        self.pushButton_SetPhoto.setObjectName("pushButton_SetPhoto")
        self.Label_SetPath = QtWidgets.QLabel(Form)
        self.Label_SetPath.setGeometry(QtCore.QRect(80, 440, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Label_SetPath.setFont(font)
        self.Label_SetPath.setObjectName("Label_SetPath")
        self.lineEdit_SetPath = QtWidgets.QLineEdit(Form)
        self.lineEdit_SetPath.setGeometry(QtCore.QRect(200, 440, 351, 31))
        self.lineEdit_SetPath.setObjectName("lineEdit_SetPath")
        self.pushButton_SetPath = QtWidgets.QPushButton(Form)
        self.pushButton_SetPath.setGeometry(QtCore.QRect(570, 440, 93, 28))
        self.pushButton_SetPath.setObjectName("pushButton_SetPath")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Label_UserName.setText(_translate("Form", "用户名:"))
        self.Label_UserMessage.setText(_translate("Form", "身   份:"))
        self.Label_UserName_2.setText(_translate("Form", "Admin"))
        self.Label_UserMassege_2.setText(_translate("Form", "管理员"))
        self.Label_Show.setText(_translate("Form", "欢迎使用C-A云自然语言分析工具!"))
        self.Label_SetPhoto.setText(_translate("Form", "词云图片模板："))
        self.lineEdit_SetPhoto.setText(_translate("Form", "默认图片模板C-A"))
        self.pushButton_SetPhoto.setText(_translate("Form", "浏览.."))
        self.Label_SetPath.setText(_translate("Form", "工具工作目录："))
        self.lineEdit_SetPath.setText(_translate("Form", "$FileDir$/Workspace"))
        self.pushButton_SetPath.setText(_translate("Form", "浏览.."))

